### ISSUE TITLE
required numpy array dtype inconsistent with standard image data ranges

### ISSUE THREAD

**Issue by michaelaye** [astropy/astroscrappy#27]
The doctext of `detect_cosmics` says that the input should be a float numpy array, but the parameter `satlevel` default is given as 65538, which indicates that the function expects a uint16 data-type?
By convention, float dtype image data should be 0.0...1.0 (or sometimes -1.0...1.0) but not use uint16 numbers up to 2**16.
Could you clarify if `detect_cosmics` requires
* a certain input range of numbers to properly work?
* a certain numpy dtype as input (help text says `float`, but as I described above, that somehow doesn't fit with satlevel default, and while testing, it seems to do something properly with a uint8 input?)
* both of the above?

Thanks!

**Comment by cmccully** [comment]
@michaelaye Sorry for the long delay on this. The default is to use the standard uint16 bit value, but it is only the default. The code automatically converts the image to a 32-bit floating point internally. For making a cosmic ray mask, this is nearly always sufficient. If you need higher precision for some reason, we should talk. In that case, I would recommend not using the "cleaned" array, but only take the mask. Feel free to close this if it answers your question.

**Comment by michaelaye** [comment]
Thanks.
Just to be clear, that seems to mean that `detect_cosmics` works with all input ranges and all input data-types?

**Comment by cmccully** [comment]
As far as I know it should. If you run into issues let me know. You just
need to set the saturate and gain values accordingly.

**Comment by cmccully** [comment]
@michaelaye Does this answer your question so I can close this?

**Comment by cmccully** [comment]
Closing this. Let me know if I need to reopen.
