### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by astrofrog** [astropy/astroscrappy#67]
The last release is from 2018 and uses astropy-helpers. It currently fails to install in a clean environment as at the time it did not use pyproject to define build-time dependencies. It might be time for a new release?

**Comment by saimn** [comment]
@astrofrog - Yes, we are almost there, see #66

**Comment by cmccully** [comment]
@astrofrog I have just released 1.1.0

**Comment by saimn** [comment]
Oops, it seems the upload job did not start: https://github.com/astropy/astroscrappy/actions/runs/1478513857

**Comment by saimn** [comment]
It's done !
https://pypi.org/project/astroscrappy/1.1.0/#files

**Comment by astrofrog** [comment]
Thanks!
